spring:
  application:
    name: shrinker

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: prod

server:
  address: 0.0.0.0
  port: 8001



logging:
  leve:
    com:
      eclipsett:
        shrinker: TRACE